services:
  db:
    image: postgres:15
    container_name: biblioteca-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=biblioteca
      - POSTGRES_PASSWORD=biblioteca123
      - POSTGRES_DB=biblioteca
    restart: unless-stopped

volumes:
  postgres_data:
